#!/bin/bash

# $Id: 907-gpm 3213 2006-11-11 11:39:16Z manuel $

set -e
cd $PKGDIR

patch -Np1 -i ../gpm-1.20.1-segfault-1.patch
patch -Np1 -i ../gpm-1.20.1-silent-1.patch
./configure --prefix=/usr --sysconfdir=/etc
LDFLAGS="$LDFLAGS -lm" make
make install
cp -v conf/gpm-root.conf /etc
ldconfig

exit
