#!/bin/bash

# $Id: 904-unzip 3350 2007-04-13 19:26:35Z manuel $

set -e
cd $PKGDIR

patch -Np1 -i ../unzip-5.52-security_fix-1.patch
make -f unix/Makefile LOCAL_UNZIP=-D_FILE_OFFSET_BITS=64 linux
make prefix=/usr install

exit
